### ISSUE TITLE
Unable to deserialize Kafka Avro message 

### ISSUE THREAD

**Issue by druhin-arrcus** [confluentinc/libserdes#1]
I am using the libserdes library to produce messages to Kafka in Avro format. I am trying to use the `kafka-avro-console-consumer` to consume the same messages from Kafka. However, I get the following error: 

```
Processed a total of 1 messages
[2017-07-03 15:34:10,344] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:105)
org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```

Shouldn't the `kafka-avro-console-consumer` be able to understand these messages?

**Comment by edenhill** [comment]
@druhin-arrcus Did you resolve this issue?

**Comment by druhin-arrcus** [comment]
Yes, thanks.

**Comment by ranjithv** [comment]
How did you resolve it? I'm facing the same..

**Comment by khaireddine120** [comment]
me too

**Comment by qiao-meng-zefr** [comment]
me too

**Comment by ranjithv** [comment]
I saw one solution to use confluent lib - kafkaavroserializer/deserializer but still was getting the same problem since I could not get away not providing a schema registry url. I had the schema but the other team owned the registry and its their internal and could not get access to it.
https://docs.confluent.io/current/app-development.html

however, I got away by doing this(java consumer):
props.put("value.deserializer", "org.apache.kafka.common.serialization.ByteArrayDeserializer");
ConsumerRecord<String, byte[]> record

then with another scala code lib doing this:
val parser = new Parser
val schema = parser.parse(avro_schema_as_string)
val reader = new GenericDatumReader[GenericRecord](schema)
val decoder = DecoderFactory.get().binaryDecoder(avroByteArray, null)
val result = reader.read(null, decoder)
then
var data1 = result.get("some-key-name1").toString
var data2 = result.get("some-key-name2").toString

excuse for java/scala shift but its that way in my repo
